const $=id=>document.getElementById(id);let notes=[],faturistas=[],filtered=[],refreshing=false,confirmCallback=null;
const fields=["numero_nf","serie","data_emissao","cnpj_fornecedor","nome_fornecedor","valor_total","chave_acesso","local","produto","quantidade","transportador","faturista","lider_operacional","observacao"];
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const date=v=>v?new Date(v).toLocaleString("pt-BR"):"—";const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function api(path,options={}){const r=await fetch(path,options);if(!r.ok){let m=`Erro ${r.status}`;try{m=(await r.json()).detail||m}catch{}throw new Error(m)}return r.headers.get("content-type")?.includes("json")?r.json():r}
function toast(message,error=false){const el=$("toast");el.textContent=message;el.className=error?"show error":"show";setTimeout(()=>el.className="",3200)}
async function loadAll(silent=false){if(refreshing)return;refreshing=true;try{[notes,faturistas]=await Promise.all([api("/notas/?limit=500"),api("/faturistas/?incluir_inativos=true")]);renderBillingOptions();applyFilters();renderFaturistas();$("lastUpdate").textContent=`Atualizado ${new Date().toLocaleTimeString("pt-BR")}`;if(!silent)toast("Dados atualizados")}catch(e){toast(e.message,true)}finally{refreshing=false}}
function applyFilters(){const q=$("searchInput").value.toLowerCase().trim(),local=$("localFilter").value,bill=$("billingFilter").value;filtered=notes.filter(n=>(!local||n.local===local)&&(!bill||n.faturista===bill)&&(!q||Object.values(n).some(v=>String(v??"").toLowerCase().includes(q))));render()}
function render(){const body=$("notesTable");body.innerHTML=filtered.map(n=>`<tr>
<td class="sticky"><div class="row-actions"><button title="Editar" onclick="editNote(${n.id})">✎</button><button title="Gerar XML" onclick="downloadXML(${n.id})">↓</button><button title="Excluir" onclick="askDelete(${n.id})">×</button></div></td>
<td>${n.id}</td><td title="${esc(n.chave_acesso)}">${esc(n.chave_acesso)}</td><td>${date(n.data_cadastro)}</td><td>${date(n.data_emissao)}</td><td><strong>${esc(n.numero_nf)}</strong></td>
<td><span class="badge">${esc(n.local||"—")}</span></td><td title="${esc(n.produto)}">${esc(n.produto||"—")}</td><td>${esc(n.quantidade||"—")}</td>
<td>${esc(n.transportador||"—")}</td><td>${esc(n.faturista||"BIPE")}</td><td>${esc(n.lider_operacional||"—")}</td><td>${esc(n.nome_fornecedor)}</td><td>${esc(n.cnpj_fornecedor)}</td>
<td>${money(n.valor_total)}</td><td title="${esc(n.observacao)}">${esc(n.observacao||"—")}</td></tr>`).join("");
$("emptyState").hidden=filtered.length>0;$("resultCount").textContent=`${filtered.length} registro(s)`;$("metricTotal").textContent=notes.length;$("metricWeight").textContent=new Intl.NumberFormat("pt-BR").format(notes.reduce((s,n)=>s+(n.quantidade||0),0));$("metricValue").textContent=money(notes.reduce((s,n)=>s+(n.valor_total||0),0));$("metricPending").textContent=notes.filter(n=>!n.lider_operacional).length}
function renderBillingOptions(){const active=faturistas.filter(f=>f.ativo),current=$("billingFilter").value;$("billingFilter").innerHTML='<option value="">Todos os faturistas</option>'+active.map(f=>`<option>${esc(f.nome)}</option>`).join("");$("billingFilter").value=current;$("faturista").innerHTML=active.map(f=>`<option>${esc(f.nome)}</option>`).join("")}
function renderFaturistas(){$("billingList").innerHTML=faturistas.map(f=>`<div class="billing-item"><div class="${f.ativo?"":"inactive"}"><strong>${esc(f.nome)}</strong><small>${f.ativo?"Ativo":"Desativado"}</small></div><div>${f.nome==="BIPE"?"Padrão do app":`<button class="secondary" onclick="toggleBilling(${f.id},${!f.ativo})">${f.ativo?"Desativar":"Reativar"}</button>`}</div></div>`).join("")}
function fillNote(n,mode="edit"){fields.forEach(k=>{const el=$(k);let v=n[k]??"";if(k==="data_emissao"&&v)v=v.slice(0,16);el.value=v});$("noteId").value=mode==="edit"?n.id:"";$("noteMode").textContent=mode==="edit"?"EDIÇÃO DE NOTA":"CONFERÊNCIA DA LEITURA";$("noteTitle").textContent=mode==="edit"?`Editar NF ${n.numero_nf}`:"Conferir nota fiscal";$("noteDialog").showModal()}
window.editNote=id=>fillNote(notes.find(n=>n.id===id));
async function downloadReport(params,name){try{const r=await fetch(`/relatorio/?${params}` ,{method:"POST"});if(!r.ok){const data=await r.json();throw new Error(data.detail||`Erro ${r.status}`)}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e){toast(e.message,true)}}
window.downloadXML=id=>downloadReport(`nota_id=${id}&formato=xml`,`nota_fiscal_${id}.xml`);
window.askDelete=id=>confirm("Excluir nota fiscal?","A nota será removida permanentemente.",async()=>{try{await api(`/notas/${id}/`,{method:"DELETE"});toast("Nota excluída");loadAll(true)}catch(e){toast(e.message,true)}})
window.toggleBilling=async(id,ativo)=>{const f=faturistas.find(x=>x.id===id);try{await api(`/faturistas/${id}/`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({nome:f.nome,ativo})});toast(ativo?"Faturista reativado":"Faturista desativado");loadAll(true)}catch(e){toast(e.message,true)}}
function confirm(title,message,callback){$("confirmTitle").textContent=title;$("confirmMessage").textContent=message;confirmCallback=callback;$("confirmDialog").showModal()}
$("confirmCancel").onclick=()=>$("confirmDialog").close();$("confirmAction").onclick=()=>{ $("confirmDialog").close();confirmCallback?.()};
$("noteForm").addEventListener("submit",async e=>{e.preventDefault();const payload={};fields.forEach(k=>payload[k]=$(k).value||null);payload.valor_total=Number(payload.valor_total||0);payload.quantidade=payload.quantidade?Number(payload.quantidade):null;payload.caminho_arquivo_imagem=null;const id=$("noteId").value;try{await api(id?`/notas/${id}/`:"/notas/",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});$("noteDialog").close();toast(id?"Nota atualizada":"Nota cadastrada");loadAll(true)}catch(err){toast(err.message,true)}});
$("scanForm").addEventListener("submit",async e=>{e.preventDefault();try{const result=await api("/barcode-nf/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({codigo_barras:$("scanKey").value})});const n={...result.nota,local:$("scanLocal").value,faturista:"BIPE"};$("scanDialog").close();fillNote(n,"create")}catch(err){toast(err.message,true)}});
$("billingForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("/faturistas/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nome:$("billingName").value})});$("billingName").value="";toast("Faturista cadastrado");loadAll(true)}catch(err){toast(err.message,true)}});
$("openScan").onclick=()=>{$("scanForm").reset();$("scanDialog").showModal()};$("openFaturistas").onclick=()=>$("faturistasDialog").showModal();document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());$("refreshButton").onclick=()=>loadAll();$("searchInput").oninput=applyFilters;$("localFilter").onchange=applyFilters;$("billingFilter").onchange=applyFilters;
$("downloadAll").onclick=()=>downloadReport("formato=xml","notas_fiscais.xml");
loadAll(true);setInterval(()=>loadAll(true),4000);
